## 1. Импорт NumPy

Обычно библиотеку импортируют под коротким именем `np`.

In [50]:
import numpy as np

print("numpy version:", np.__version__)

numpy version: 2.5.2


## 2. Создание массивов

Главный объект NumPy — `ndarray`.

Самый простой способ создать массив — передать список в `np.array()`.

In [28]:
a = np.array([10, 20, 30, 40, 50])

print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


У массива есть полезные свойства:

- `a.size` — количество элементов;
- `a.ndim` — количество измерений;
- `a.dtype` — тип элементов.

In [29]:
print("size:", a.size)
print("ndim:", a.ndim)
print("dtype:", a.dtype)

size: 5
ndim: 1
dtype: int64


### Несколько удобных способов создать массив

`np.arange()` похож на обычный `range()`.

`np.linspace()` создаёт заданное количество равномерно расположенных чисел.

In [30]:
print("arange:", np.arange(0, 10, 2))
print("linspace:", np.linspace(0, 1, 5))
print("zeros:", np.zeros(5))
print("ones:", np.ones(5))

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1.]


## 3. Типы данных

В отличие от обычного списка Python, NumPy-массив обычно хранит элементы **одного типа**.

Тип можно посмотреть через `dtype`.

In [31]:
integers = np.array([1, 2, 3])
floats = np.array([1.0, 2.5, 3.7])

print(integers.dtype)
print(floats.dtype)

int64
float64


Тип можно указать явно.

In [32]:
a = np.array([1, 2, 3], dtype=float)

print(a)
print(a.dtype)

[1. 2. 3.]
float64


## 4. Индексация и срезы

Индексация очень похожа на работу со списками Python.

In [33]:
a = np.array([10, 20, 30, 40, 50])

print("Первый:", a[0])
print("Последний:", a[-1])
print("Срез:", a[1:4])
print("Каждый второй:", a[::2])

Первый: 10
Последний: 50
Срез: [20 30 40]
Каждый второй: [10 30 50]


Элементы можно изменять.

In [34]:
a = np.array([10, 20, 30, 40, 50])

a[0] = 100
a[2:4] = 0

print(a)

[100  20   0   0  50]


## 5. Операции над массивами

Одна из главных идей NumPy — выполнять операцию **сразу над всем массивом**.

В обычном Python для этого часто используют цикл или list comprehension.

In [35]:
numbers = [1, 2, 3, 4, 5]

python_result = [x * 2 for x in numbers]

print(python_result)

[2, 4, 6, 8, 10]


В NumPy можно написать короче:

In [36]:
numbers = np.array([1, 2, 3, 4, 5])

print(numbers * 2)
print(numbers + 10)
print(numbers - 1)
print(numbers ** 2)

[ 2  4  6  8 10]
[11 12 13 14 15]
[0 1 2 3 4]
[ 1  4  9 16 25]


Такие операции выполняются **поэлементно**.

Можно использовать и готовые математические функции:

In [37]:
numbers = np.array([1, 4, 9, 16, 25])

print("sqrt:", np.sqrt(numbers))

sqrt: [1. 2. 3. 4. 5.]


## 6. Простые встроенные функции

NumPy содержит много готовых функций для обработки числовых данных.

In [38]:
data = np.array([7, 2, 9, 4, 6, 1])

print("Сумма:", np.sum(data))
print("Среднее:", np.mean(data))
print("Минимум:", np.min(data))
print("Максимум:", np.max(data))

Сумма: 29
Среднее: 4.833333333333333
Минимум: 1
Максимум: 9


Иногда нужен не сам минимум или максимум, а **его индекс**.

In [39]:
data = np.array([7, 2, 9, 4, 6, 1])

print("Индекс минимума:", np.argmin(data))
print("Индекс максимума:", np.argmax(data))

Индекс минимума: 5
Индекс максимума: 2


Ещё несколько несложных функций:

In [40]:
data = np.array([4, 2, 7, 2, 9, 4, 2])

print("sort:", np.sort(data))
print("unique:", np.unique(data))
print("round:", np.round(np.array([1.234, 5.678, 9.876]), 1))

sort: [2 2 2 4 4 7 9]
unique: [2 4 7 9]
round: [1.2 5.7 9.9]


## 7. Сравнения

Если сравнить массив с числом, NumPy сравнит с ним **каждый элемент**.

In [41]:
a = np.array([1, 5, 8, 2, 10, 3])

print(a > 4)

[False  True  True False  True False]


Получаем булевый массив из `True` и `False`.

Можно строить более сложные условия.

Для массивов используются:

- `&` — И
- `|` — ИЛИ
- `~` — НЕ

Каждое отдельное сравнение лучше брать в скобки.

In [42]:
a = np.array([1, 5, 8, 2, 10, 3])

condition = (a >= 3) & (a <= 8)

print(condition)

[False  True  True False False  True]


## 8. Фильтрация

Булевый массив можно использовать как **маску**.

NumPy оставит только те элементы, для которых условие равно `True`.

In [43]:
a = np.array([1, 5, 8, 2, 10, 3])

print("Больше 4:", a[a > 4])
print("Чётные:", a[a % 2 == 0])
print("От 3 до 8:", a[(a >= 3) & (a <= 8)])

Больше 4: [ 5  8 10]
Чётные: [ 8  2 10]
От 3 до 8: [5 8 3]


По маске можно не только получать значения, но и изменять их.

In [44]:
a = np.array([1, 5, 8, 2, 10, 3])

a[a > 5] = 0

print(a)

[1 5 0 2 0 3]


## 9. `np.any()` и `np.all()`

`np.any()` проверяет, есть ли **хотя бы один** `True`.

`np.all()` проверяет, являются ли **все** значения `True`.

In [45]:
a = np.array([2, 4, 6, 8])

print("Есть число > 5:", np.any(a > 5))
print("Все положительные:", np.all(a > 0))
print("Все чётные:", np.all(a % 2 == 0))

Есть число > 5: True
Все положительные: True
Все чётные: True


## 10. Сравнение скорости с обычным Python

Теперь сравним обычный Python и NumPy на большой последовательности чисел.

Для измерения времени используем `time.perf_counter()`.

In [46]:
from time import perf_counter

N = 10_000_000

python_data = list(range(N))
numpy_data = np.arange(N)

In [47]:
start = perf_counter()

python_result = [x ** 0.5 for x in python_data]

python_time = perf_counter() - start

print(f"Обычный Python: {python_time:.6f} секунд")

Обычный Python: 0.441004 секунд


In [48]:
start = perf_counter()

numpy_result = np.sqrt(numpy_data)

numpy_time = perf_counter() - start

print(f"NumPy: {numpy_time:.6f} секунд")

NumPy: 0.017408 секунд


In [49]:
print(f"NumPy быстрее примерно в {python_time / numpy_time:.1f} раз")

NumPy быстрее примерно в 25.3 раз
